language: node_js
node_js:
  - 11
cache:
  yarn: true
  directories:
    - "node_modules"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
  - rm -f .yarnrc
before_script:
  # - yarn cache clean @types/react-dom
  - yarn bootstrap
  - yarn build
after_success:
  - yarn global add codecov
  - codecov
