name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: sergioramos/yarn-actions/install@master
      with:
        frozen-lockfile: true
    - name: install, build, and test
      run: |
        rm -f .yarnrc
        yarn
        yarn bootstrap
        yarn run build
        yarn test
        npx codecov
      env:
        CI: true
